name: Scrape Jobs

permissions:
  contents: write  # Allow write access to the repository contents

on:
  schedule:
    - cron: '7 * * * *'  # Runs hourly at minute 7
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'


      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install

      - name: Check if it's midnight ET
        id: check_time
        run: |
          CURRENT_TIME=$(TZ="America/New_York" date +%H)
          if [ "$CURRENT_TIME" -eq 23 ]; then
            echo "It's 11PM ET."
            echo "run_scraper=true" >> $GITHUB_ENV
          else
            echo "It's not 11PM ET."
            echo "run_scraper=false" >> $GITHUB_ENV
          fi

      - name: Run the scraper
        if: env.run_scraper == 'true'
        run: |
          python scraper.py

      - name: Commit and push changes
        if: env.run_scraper == 'true'
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          git add data/job_listings_*.csv
          git commit -m "Update job listings"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
