name: Scrape Jobs

permissions:
  contents: write  # Allow write access to the repository contents

on:
  schedule:
    - cron: '21 * * * *'  # Runs hourly at minute 21
    #- cron: "38 * * * *"  # Runs hourly at minute 38
  workflow_dispatch:
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install
          
      - name: Run the scraper
        run: |
          python scraper.py

      - name: Commit and push changes
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          git add data/job_listings_*.csv
          git commit -m "Update job listings"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
